# Generated by Django 5.2.4 on 2025-08-30 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userprofile_options_userprofile_is_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('target_url', models.URLField(blank=True)),
                ('cta_text', models.CharField(default='Learn More', max_length=50)),
                ('position', models.CharField(choices=[('top', 'Top Banner'), ('mid_content', 'Middle Content'), ('sidebar', 'Sidebar'), ('sidebar_bottom', 'Sidebar Bottom'), ('bottom', 'Bottom Banner')], default='top', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('show_timer', models.BooleanField(default=False, help_text='Show countdown timer on ad')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['-created_at'],
            },
        ),
    ]
