# Generated by Django 5.2.4 on 2025-09-04 08:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcontent',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Add YouTube video link here', null=True),
        ),
        migrations.AlterField(
            model_name='uploadedcontent',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('audio', 'Audio'), ('image', 'Image'), ('youtube', 'YouTube')], default='pdf', max_length=10),
        ),
        migrations.AlterField(
            model_name='uploadedcontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.content_file_path),
        ),
    ]
