# Generated by Django 5.2.7 on 2025-10-19 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education Levels',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#4361ee', help_text='Hex color for subject badge', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='uploadedcontent',
            options={'ordering': ['-uploaded_at'], 'permissions': [('can_feature_resource', 'Can feature resource'), ('can_approve_resource', 'Can approve resources'), ('can_export_resources', 'Can export resources data')], 'verbose_name': 'Educational Resource', 'verbose_name_plural': 'Educational Resources'},
        ),
        migrations.AddField(
            model_name='uploadedcontent',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='uploadedcontent',
            name='curriculum_alignment',
            field=models.TextField(blank=True, help_text='How this aligns with curriculum'),
        ),
        migrations.AddField(
            model_name='uploadedcontent',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=15),
        ),
        migrations.AddField(
            model_name='uploadedcontent',
            name='estimated_duration',
            field=models.PositiveIntegerField(default=0, help_text='Estimated time in minutes'),
        ),
        migrations.AddField(
            model_name='uploadedcontent',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedcontent',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uploadedcontent',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedcontent',
            name='learning_objectives',
            field=models.TextField(blank=True, help_text='What students will learn'),
        ),
        migrations.AddField(
            model_name='uploadedcontent',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedcontent',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='Required prior knowledge'),
        ),
        migrations.AddField(
            model_name='uploadedcontent',
            name='requires_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedcontent',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedcontent',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadedcontent',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadedcontent',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedcontent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=15),
        ),
        migrations.AddField(
            model_name='uploadedcontent',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500),
        ),
        migrations.AddField(
            model_name='uploadedcontent',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated thumbnail for videos', null=True, upload_to='content/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='uploadedcontent',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('audio', 'Audio'), ('image', 'Image'), ('youtube', 'YouTube'), ('document', 'Document'), ('presentation', 'Presentation'), ('spreadsheet', 'Spreadsheet')], default='pdf', max_length=15),
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_history', to='resources.uploadedcontent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Download History',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddField(
            model_name='uploadedcontent',
            name='education_levels',
            field=models.ManyToManyField(blank=True, to='resources.educationlevel'),
        ),
        migrations.CreateModel(
            name='ResourceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='resources.uploadedcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Resource Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='uploadedcontent',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.subject'),
        ),
        migrations.AddIndex(
            model_name='uploadedcontent',
            index=models.Index(fields=['status', 'is_public'], name='resources_u_status_e4b821_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedcontent',
            index=models.Index(fields=['content_type'], name='resources_u_content_f42f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedcontent',
            index=models.Index(fields=['uploaded_by', 'uploaded_at'], name='resources_u_uploade_ccda45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcereview',
            unique_together={('resource', 'user')},
        ),
    ]
